FIRST_NAME = "NEEL"
MIDDLE_NAME = "KARAN"
LAST_NAME = "BIND"

FULL_NAME_1 = " NEEL" "KARAN" "BIND"
FULL_NAME_2 = "NEEL" + "KARAN" + "BIND"
FULL_NAME_3 = FIRST_NAME + " " + MIDDLE_NAME + " " + LAST_NAME
FULL_NAME_4 = F"{FIRST_NAME} {MIDDLE_NAME} {LAST_NAME}"
FULL_NAME_7 = f"{FIRST_NAME} {8-2} {MIDDLE_NAME} HI {LAST_NAME} G"

print(FULL_NAME_1)
print(FULL_NAME_2)
print(FULL_NAME_3)
print(FULL_NAME_4)
print(FULL_NAME_7)



